version: 2

sources:
  - name: PREVENTIVE_HEALTHCARE
    description: "Raw data sources"
    database: PREVENTIVE_HEALTHCARE
    schema: LENGTHOFSTAY
    tables:
      - name: ADMISSIONS
      - name: DIAGNOSES_ICD
      - name: ICUSTAYS
      - name: PATIENTS
      - name: SERVICES
      - name: TRANSFERS

